# vim: set fileencoding=utf-8
"""
pythoneda/sandbox/artifact/application/sandbox_app.py

This file defines the SandboxApp class.

Copyright (C) 2023-today rydnr's pythoneda-sandbox-artifact/python-application

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import asyncio
from pythoneda.shared.application import enable
from pythoneda.shared.artifact import Artifact
from pythoneda.shared.artifact.application import LocalArtifactApp
from pythoneda.sandbox.artifact.infrastructure import LocalSandbox


from pythoneda.shared.artifact.infrastructure.cli import (
    RepositoryFolderCli,
)
from pythoneda.shared.artifact.infrastructure.dbus import (
    ArtifactDbusSignalEmitter,
    ArtifactDbusSignalListener,
)


@enable(ArtifactDbusSignalEmitter)
@enable(ArtifactDbusSignalListener)
@enable(RepositoryFolderCli)
class SandboxApp(LocalArtifactApp):
    """
    Runs the Sandbox artifact PythonEDA app.

    Class name: SandboxApp

    Responsibilities:
        - Runs the Sandbox artifact PythonEDA app.

    Collaborators:
        - Command-line handlers from pythoneda-shared-artifact/infrastructure
    """

    def __init__(self):
        """
        Creates a new SandboxApp instance.
        """
        # sandbox_banner is automatically generated by pythoneda-sandbox-artifact-def/python-application's flake.
        try:
            from pythoneda.sandbox.artifact.application.sandbox_banner import (
                SandboxBanner,
            )

            banner = SandboxBanner()
        except ImportError:
            banner = None

        super().__init__(banner, __file__)

    @classmethod
    def artifact_class(cls) -> type[Artifact]:
        """
        Retrieves the subclass of Artifact.
        :return: Such class.
        :rtype: type[Artifact]
        """
        return LocalSandbox


if __name__ == "__main__":
    asyncio.run(SandboxApp.main())
# vim: syntax=python ts=4 sw=4 sts=4 tw=79 sr et
# Local Variables:
# mode: python
# python-indent-offset: 4
# tab-width: 4
# indent-tabs-mode: nil
# fill-column: 79
# End:
